### PR TITLE
Update Makefile

### PR DESCRIPTION
**Pull request by Francy93**
Now compatible with UNIX-LIKE (Mac_OS and Linux) and WINDOWS (Cygwin and MinGW).
Now ready for ultimate checks before merging to the master branch.

### CODE REVIEW

**Comment by danielpinto8zz6** [comment]
Hi, can you update also C Makefile?

**Comment by Francy93** [comment]
> Hi, can you update also C Makefile?

The new version I am about to upload should be fine for both, you just have to change the first variable value (SRCEXT) from "cpp" to "c".
Just, please, make sure you have further tests before any possible merging to the master branch.

**Comment by danielpinto8zz6** [comment]
Thank you, will test this weekend

**Comment by danielpinto8zz6** [comment]
Hi, did you tested this on linux? 

The make command should create all necessary folders, instead of failing

**Comment by Francy93** [comment]
> Hi, did you tested this on linux?
> 
> The make command should create all necessary folders, instead of failing

Just tested on Ubuntu and fixed some compatibility issues

**Comment by danielpinto8zz6** [comment]
Look good, merged now, thanks for your contribution

**Pull request merged**
